// Generated by Cadence Encounter(R) RTL Compiler RC11.10 - v11.10-p005_1
tclmode
set env(RC_VERSION) "RC11.10 - v11.10-p005_1"
vpxmode
set dofile abort exit
usage -auto
set log file fv/MACRO_FUNCTION/rtl_to_g1_withoutovf.log -replace
// tclmode
// set env(CDN_SYNTH_ROOT) /home/vitor/Desktop/cadence/RC11.10/tools.lnx86
// vpxmode
tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
if {$ver >= 08.10} {
  vpx set naming style rc
}
vpxmode
set naming rule "%s[%d]" -instance_array
set naming rule "%s_reg" -register -golden
set naming rule "%L.%s" "%L[%d].%s" "%s" -instance
set naming rule "%L.%s" "%L[%d].%s" "%s" -variable
set undefined cell black_box -noascend -both
set undriven signal Z -golden

add search path -library . /home/vitor/Desktop/cadence/Library/NangateOpenCellLib_45nm/Front_End/Liberty/ECSM/ /home/vitor/Desktop/cadence/Library/NangateOpenCellLib_45nm/Back_End/lef/
read library -statetable -liberty -pg_pin -both  \
	NangateOpenCellLibrary_worst_low_ecsm.lib

add search path -design ../rtl
read design -rangeconstraint -configuration  -enumconstraint -golden -lastmod -noelab \
	-vhdl 93 \
		../rtl/MACRO_FUNCTION.vhd

elaborate design -golden -root MACRO_FUNCTION

read design -verilog -revised -lastmod -noelab \
	-unzip fv/MACRO_FUNCTION/g1.v.gz

elaborate design -revised -root MACRO_FUNCTION

substitute blackbox model -golden
report design data
report black box

uniquify -all -nolib
set flatten model -seq_constant -seq_constant_x_to 0
set flatten model -nodff_to_dlat_zero -nodff_to_dlat_feedback
// set parallel option -threads 4 -license xl
set analyze option -auto

write hier_compare dofile fv/MACRO_FUNCTION/hier_rtl_to_g1_withoutovf.do \
	-noexact_pin_match -constraint -usage -replace -run_hier \
	-prepend_string "analyze datapath -module -verbose; usage; analyze datapath -verbose"
run hier_compare fv/MACRO_FUNCTION/hier_rtl_to_g1_withoutovf.do
usage
// report hier_compare result -flattened
set system mode lec
tclmode
puts "No of diff points    = [get_compare_points -diff -count]"
if {[get_compare_points -diff -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
#     foreach i [get_compare_points -diff] {
#         vpx report test vector [get_keypoint $i]
#         puts "     ----------------------------"
#     }
}
vpxmode
exit -force
